### ISSUE TITLE
KeyError: 'norm_coord'    c = batch['norm_coord']

### ISSUE THREAD

**Issue by gaopeng-eugene** [Cadene/murel.bootstrap.pytorch#1]
when i run the following command line, I found the error below.

python -m bootstrap.run -o murel/options/vqa2/murel.yaml

 c = batch['norm_coord']
KeyError: 'norm_coord'

Here is the keys of batch:
dict_keys(['index', 'question_id', 'question', 'lengths', 'image_name', 'visual', 'nb_regions', 'answer_id', 'class_id', 'answer', 'question_type'])

Thank you for your amazing code.

**Comment by Cadene** [comment]
Hi @gaopeng-eugene,

Thanks for your interest :)
My mistake, I just uploaded a new version of the features.

```
mkdir -p data/vqa/coco/extract_rcnn
cd data/vqa/coco/extract_rcnn
wget http://data.lip6.fr/cadene/block/coco/extract_rcnn/2018-04-27_bottom-up-attention_fixed_36.tar
tar -xvf 2018-04-27_bottom-up-attention_fixed_36.tar
```
