### ISSUE TITLE
FileNotFoundError when load image features.

### ISSUE THREAD

**Issue by ghost** [Cadene/murel.bootstrap.pytorch#2]
When I run `python -m bootstrap.run -o murel/options/vqa2/murel.yaml` , I found the error below.
`FileNotFoundError: [Errno 2] No such file or directory: 'data/vqa/coco/extract_rcnn/2018-04-27_bottom-up-attention_fixed_36/COCO_train2014_000000010083.jpg.pth'`
 And then I found that there are 37,695 files in 'extract_rcnn' folder.
Is the feature file incomplete?

**Comment by Cadene** [comment]
That's strange. Did you try to download the tar file again?

```
$ du -h block/coco/extract_rcnn$ du -h 2018-04-27_bottom-up-attention_fixed_36.tar
57G	2018-04-27_bottom-up-attention_fixed_36.tar
```

**Comment by ghost** [comment]
> That's strange. Did you try to download the tar file again?
> 
> ```
> $ du -h block/coco/extract_rcnn$ du -h 2018-04-27_bottom-up-attention_fixed_36.tar
> 57G	2018-04-27_bottom-up-attention_fixed_36.tar
> ```

I re-downloaded the tar file and everything goes will。Thanks!

**Comment by Cadene** [comment]
You're welcome
