### ISSUE TITLE
How long does it take to train the models?

### ISSUE THREAD

**Issue by gaopeng-eugene** [Cadene/murel.bootstrap.pytorch#3]

**Comment by Cadene** [comment]
For the complete murel model with the pairwise module and three steps, it can take 1 day on two gpus.

**Comment by gaopeng-eugene** [comment]
Hi

Will you be able to share the training log for TDIUC and VQACP2?

**Comment by gaopeng-eugene** [comment]
Hi, I can train TDIUC and VQA2 with your code but not for VQACP2. Could you share VQACP2 log first, if possible. I will share the TDIUC log file after finished training.

**Comment by Cadene** [comment]
@gaopeng-eugene Did you solve your issue?

What was the issue with VQACP2?

**Comment by Zzmonica** [comment]
> For the complete murel model with the pairwise module and three steps, it can take 1 day on two gpus.

I use the same configuration, it takes almost 4.5 hours per epoch, and you know here is 25 epoches in total for training procedure,and I use 4 GeForce GTX 1080 GPU for training. 
Is that normal？

**Comment by Simon98-AI** [comment]
> > For the complete murel model with the pairwise module and three steps, it can take 1 day on two gpus.
> 
> I use the same configuration, it takes almost 4.5 hours per epoch, and you know here is 25 epoches in total for training procedure,and I use 4 GeForce GTX 1080 GPU for training.
> Is that normal？

Hi, i have some questions. When training based on its default parameters (  dropout_input: 0.1, dropout_pre_lin: 0.0, dropout_output: 0.0), Isn't that overfitting? when I training the model , the val score is only 0.24.
