### ISSUE TITLE
'block' has no attribute 'factory_fusion'

### ISSUE THREAD

**Issue by HayeonLee** [Cadene/murel.bootstrap.pytorch#4]
Hi! Thanks for providing a good framework.

When I execute the code on VQA-CPv2 dataset, 
I got error 'block' has no attribute 'factory_fusion'
![image](https://user-images.githubusercontent.com/19198395/54546097-61957000-49e6-11e9-8bd0-b8600b1503a8.png)
Could you help me?

**Comment by Cadene** [comment]
Thanks for submitting this issue. It should be fixed.

```
pip install --upgrade block.bootstrap.pytorch
```

```python
import block
print(block.__version__) # 0.1.4
block.factory_fusion
```

**Comment by HayeonLee** [comment]
Thanks!
