### ISSUE TITLE
Key Error 'visual'

### ISSUE THREAD

**Issue by HayeonLee** [Cadene/murel.bootstrap.pytorch#5]
I got keyerror 'visual' during executing code on vqa-cp2 dataset..! Could help me?
![image](https://user-images.githubusercontent.com/19198395/54605735-4893ca00-4a8d-11e9-9b5e-76984912b543.png)

**Comment by Cadene** [comment]
@HayeonLee That's strange :/

Did you solve the issue?

I would add `import ipdb;ipdb.set_trace()` in murel_net.py just before line 96 to inspect the content of `batch`. It could be due to a different implementation of the `torch.nn.DataParallel`.

What is your version of pytorch? Ours is `1.0.x`.
