### ISSUE TITLE
Error while trying to train or validate

### ISSUE THREAD

**Issue by archanray** [Cadene/murel.bootstrap.pytorch#8]
Hi, thanks for the code. 

I am trying to re-train MuRel. I got the following error: `Object arrays cannot be loaded when allow_pickle=False`

Attached is the output log. Please let me know if I'm doing something incorrectly.

Command: `CUDA_VISIBLE_DEVICES=4,5,6,7 python -m bootstrap.run -o murel/options/vqa2/murel.yaml 2>&1 | tee murel_output.txt`

[murel_output.txt](https://github.com/Cadene/murel.bootstrap.pytorch/files/3287792/murel_output.txt)

**Comment by Cadene** [comment]
@LousyLory hi, thanks for your interest. I don't know what cause this issue.

Did you try to debug by adding `import pdb;pdb.set_trace()` in `/home/ubuntu/anaconda3/envs/murel/lib/python3.7/site-packages/skipthoughts/skipthoughts.py` (line 61)?

There is an issue when the pretrained skipthoughts parameters are loaded in numpy... :/

**Comment by archanray** [comment]
I fixed this by doing the following:
 in file `/home/ubuntu/anaconda3/envs/murel/lib/python3.7/site-packages/skipthoughts/skipthoughts.py`

line 61:
original: `params = numpy.load(path_params, encoding='latin1')`
modified: `params = numpy.load(path_params, encoding='latin1', allow_pickle=True)`

line 70:
original: `params = numpy.load(path_params, encoding='latin1')`
modified: `params = numpy.load(path_params, encoding='latin1', allow_pickle=True)`

I think the issue stems from a numpy version mismatch. I am using `1.16.4`.
